name: fmr
favicon: null
layout_spectrum: 0.43768196483142674
typography_spectrum: 0.6795200444757938
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#300700'
    - '#dfcdb2'
    - '#bf2618'
    - '#9e8a87'
    - '#60413c'
  brandStrength: 0.5785261613782495
  lightness: 0.9017098345793784
  saturation: 0.08867906825616956
  rhythmicContrast: 0.381528944009915
purpose: []
