typography_spectrum: 0.45674012391828
color:
  brandColors:
    - '#300700'
    - '#dfcdb2'
    - '#bf2618'
    - '#9e8a87'
    - '#60413c'
  brandStrength: 0.5785261613782495
  lightness: 0.9017098345793784
  saturation: 0.08867906825616956
  rhythmicContrast: 0.381528944009915
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.921107797883451
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cb604559-7b50-4099-a3c9-f94d71496d6e.png
name: fmr
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Brewery
    url: fmr.beer
    type: external
favicon: null
purpose: []
